### ISSUE TITLE
index.html?

### ISSUE THREAD

**Issue by nanoeray** [barbarbar338/pinkie-api#6]
"message": "ENOENT: no such file or directory, stat 'C:\\Users\\eray_\\Desktop\\pinkie-api-master\\src\\public\\index.html'"
şeklinde hata vermekte

**Comment by barbarbar338** [comment]
Serveri nasıl çalıştırıyorsun?

**Comment by nanoeray** [comment]
yarn start:dev ile development ortamında denedim. api request atıldığında index.html istiyor nedense. discord level için çalıştırmayı denedim sanırım gerekli image kütüphanesi mevcut değil bunda sorunu sonrasında kendim bot içeriğine custom api yazarak hallettim teşekkürler. ilgili geliştirmeleri bot reposunda sizinle paylaştım.
